wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.10
    start_time: 1656014327
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      4: 3.7.10
      5: 0.12.19
      6: 4.20.1
      8:
      - 1
      - 2
      - 5
