wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.10
    start_time: 1656014723
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      4: 3.7.10
      5: 0.12.19
      8:
      - 1
      - 2
      - 5
